version: "3.8"
services:
  api-server:
    build:
      context: ./nyang8ja-api
    ports:
      - "8080:8080"
    networks:
      - backend

  ai-server:
    build:
      context: ./nyang8ja-ai
    ports:
      - "8000:8000"
    networks:
      - backend

  web-server:
    build:
      context: ./nyang8ja-webserver
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - api-server
      - ai-server

networks:
  backend: