name: Deploy Production Environment
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2

jobs:
  api-server-deploy:
    runs-on: ubuntu-latest
    steps:
      # Repo checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          submodules: true

      # JDK 환경 셋팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      # Gradle Permission - (수정필요)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build Image - (수정필요)
      - name: Gradle build
        run: |
          ./gradlew globalCopyConfig
          ./gradlew nyang8ja-api:build -x test

      # AWS Config
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
